#https://medium.com/@carlosviniciustenorio/deploying-net-applications-mysql-and-adminer-in-k8s-af584809332c
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: adminer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: adminer-db
spec:
  type: LoadBalancer
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080