apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: {{ .Values.container.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: {{ .Values.container.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nodeport.port }}
      targetPort: {{ .Values.nodeport.targetport}}
      nodePort: {{ .Values.nodeport.nport}}
  selector:
    app: {{ .Values.app.name }}
